### ISSUE TITLE
Correctly define 'generate_csv' in 'generator_data.py'

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/login-report#102]
We need to correctly define the `generate_csv` method within `generator_data.py`.  Specifically, we need to eliminate the following traceback error:

``` bash
$ python app.py
Traceback (most recent call last):
  File "app.py", line 6, in <module>
    from package.load_data import process_report
  File "/var/www_interviews/html/login-report/package/load_data.py", line 8, in <module>
    from package.generator.generator_data import Generate_Data
  File "/var/www_interviews/html/login-report/package/generator/generator_data.py", line 76
    fp.writerow([column['email'], column['login_last'], column['login_first'], column['count_success'], column['count_failure'])
                                                                                                                               ^
SyntaxError: invalid syntax
```

**Comment by jeff1evesque** [comment]
We need to resolve the following traceback error:

``` bash
$ python app.py
 * Running on http://127.0.0.1:5000/
 * Restarting with reloader
global name 'path' is not defined
127.0.0.1 - - [05/Mar/2015 09:30:03] "POST /generate-report/ HTTP/1.1" 200 -
```
